Config.Clothes = {
    availableClothes = {
        newbie = {'newbie', 'pohreb', 'svatba'},
        waiter = {'newbie', 'waiter', 'pohreb', 'svatba'},
        barman = {'newbie', 'waiter', 'barman', 'probarman', 'pohreb', 'svatba'},
        probarman = {'newbie', 'waiter', 'barman', 'probarman', 'pohreb', 'svatba'},
        lowerboss1 = {'newbie', 'waiter', 'barman', 'probarman', 'lowerboss1', 'boss2', 'pohreb', 'svatba'},
        boss = {'newbie', 'waiter', 'barman', 'probarman', 'lowerboss1', 'boss', 'boss2', 'pohreb', 'svatba'},
    },

    male = {
        pohreb = {
            tshirt_1 = 6,  tshirt_2 = 2,
            torso_1 = 11,   torso_2 = 1,
            decals_1 = 0,   decals_2 = 0,
            arms = 11, arms_2 = 0,
            pants_1 = 33,   pants_2 = 0,
            shoes_1 = 10,   shoes_2 = 0,
            helmet_1 = -1,  helmet_2 = 0,
            chain_1 = 0,    chain_2 = 0,
            bproof_1 = 0,  bproof_2 = 0,
            mask_1 = -1,     mask_2 = 0,
            ears_1 = -1,     ears_2 = 0,
            glasses_1 = 0,  glasses_2 = 0,
            bracelets_1 = -1, bracelets_2 = 0,
            watches_1 = -1, watches_2 = 0,
        },
        svatba = {
            tshirt_1 = 6,  tshirt_2 = 0,
            torso_1 = 11,   torso_2 = 0,
            decals_1 = 0,   decals_2 = 0,
            arms = 11, arms_2 = 0,
            pants_1 = 33,   pants_2 = 0,
            shoes_1 = 22,   shoes_2 = 0,
            helmet_1 = -1,  helmet_2 = 0,
            chain_1 = 0,    chain_2 = 0,
            bproof_1 = 0,  bproof_2 = 0,
            mask_1 = -1,     mask_2 = 0,
            ears_1 = -1,     ears_2 = 0,
            glasses_1 = 0,  glasses_2 = 0,
            bracelets_1 = -1, bracelets_2 = 0,
            watches_1 = -1, watches_2 = 0,
        },
        newbie = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 0, ['torso_2'] = 3,
            ['arms'] = 65,
            ['chain_1'] = 0,
            ['pants_1'] = 99, ['pants_2'] = 8,
            ['shoes_1'] = 28, ['shoes_2'] = 0,
        },
        waiter = {
	        ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 264, ['torso_2'] = 20,
            ['arms'] = 11,
            ['chain_1'] = 0,
            ['pants_1'] = 12, ['pants_2'] = 2,
            ['shoes_1'] = 20, ['shoes_2'] = 8,
        },
        barman = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 264, ['torso_2'] = 18,
            ['arms'] = 11,
            ['chain_1'] = 0,
            ['pants_1'] = 12, ['pants_2'] = 2,
            ['shoes_1'] = 20, ['shoes_2'] = 8,
        },
        probarman = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
                ['torso_1'] = 245, ['torso_2'] = 5,
                ['arms'] = 0,
                ['chain_1'] = 0,
                ['pants_1'] = 12, ['pants_2'] = 2,
                ['shoes_1'] = 20, ['shoes_2'] = 10,
        },
        lowerboss1 = {
            tshirt_1 = 52,  tshirt_2 = 0,
            torso_1 = 25,   torso_2 = 0,
            decals_1 = 0,   decals_2 = 0,
            arms = 39, arms_2 = 0,
            pants_1 = 33,   pants_2 = 0,
            shoes_1 = 3,   shoes_2 = 0,
            helmet_1 = -1,  helmet_2 = 0,
            chain_1 = 0,    chain_2 = 0,
            bproof_1 = 0,  bproof_2 = 0,
            mask_1 = -1,     mask_2 = 0,
            ears_1 = -1,     ears_2 = 0,
            glasses_1 = 5,  glasses_2 = 0,
            bracelets_1 = -1, bracelets_2 = 0,
            watches_1 = -1, watches_2 = 0,
        },
        boss = {
            ['tshirt_1'] = 10, ['tshirt_2'] = 0,
                ['torso_1'] = 27, ['torso_2'] = 3,
                ['arms'] = 4,
                ['chain_1'] = 21,
                ['pants_1'] = 17, ['pants_2'] = 5,
                ['shoes_1'] = 10, ['shoes_2'] = 0,
        },
        boss2 = {
            ['tshirt_1'] = 10, ['tshirt_2'] = 7,
            ['torso_1'] = 32, ['torso_2'] = 0,
            ['arms'] = 4,
            ['chain_1'] = 21,
            ['pants_1'] = 17, ['pants_2'] = 1,
            ['shoes_1'] = 10, ['shoes_2'] = 0,
        },
    },
    
    female = {
        pohreb = {
            tshirt_1 = 27,  tshirt_2 = 1,
            torso_1 = 37,   torso_2 = 3,
            decals_1 = 0,   decals_2 = 0,
            arms = 0, arms_2 = 0,
            pants_1 = 8,   pants_2 = 0,
            shoes_1 = 13,   shoes_2 = 0,
            helmet_1 = -1,  helmet_2 = 0,
            chain_1 = 0,    chain_2 = 0,
            bproof_1 = 0,  bproof_2 = 0,
            mask_1 = -1,     mask_2 = 0,
            ears_1 = -1,     ears_2 = 0,
            glasses_1 = 5,  glasses_2 = 0,
            bracelets_1 = -1, bracelets_2 = 0,
            watches_1 = -1, watches_2 = 0,
        },
        svatba = {
            tshirt_1 = 27,  tshirt_2 = 0,
            torso_1 = 37,   torso_2 = 5,
            decals_1 = 0,   decals_2 = 0,
            arms = 0, arms_2 = 0,
            pants_1 = 8,   pants_2 = 0,
            shoes_1 = 13,   shoes_2 = 5,
            helmet_1 = -1,  helmet_2 = 0,
            chain_1 = 0,    chain_2 = 0,
            bproof_1 = 0,  bproof_2 = 0,
            mask_1 = -1,     mask_2 = 0,
            ears_1 = -1,     ears_2 = 0,
            glasses_1 = 5,  glasses_2 = 0,
            bracelets_1 = -1, bracelets_2 = 0,
            watches_1 = -1, watches_2 = 0,
        },
	    newbie = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 84, ['torso_2'] = 2,
            ['arms'] = 1,
            ['chain_1'] = 0,
            ['pants_1'] = 101, ['pants_2'] = 8,
            ['shoes_1'] = 10, ['shoes_2'] = 0,
        },
        waiter = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 278, ['torso_2'] = 20,
            ['arms'] = 2,
            ['chain_1'] = 0,
            ['pants_1'] = 14, ['pants_2'] = 2,
            ['shoes_1'] = 5, ['shoes_2'] = 10,
        },
        barman = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 278, ['torso_2'] = 18,
            ['arms'] = 9,
            ['chain_1'] = 0,
            ['pants_1'] = 14, ['pants_2'] = 2,
            ['shoes_1'] = 5, ['shoes_2'] = 10,
        },
        probarman = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 259, ['torso_2'] = 5,
            ['arms'] = 14,
            ['chain_1'] = 0,
            ['pants_1'] = 14, ['pants_2'] = 2,
            ['shoes_1'] = 5, ['shoes_2'] = 1,
        },
        lowerboss1 = {
            ['tshirt_1'] = 19, ['tshirt_2'] = 2,
            ['torso_1'] = 7, ['torso_2'] = 1,
            ['arms'] = 6,
            ['chain_1'] = 0,
            ['pants_1'] = 31, ['pants_2'] = 0,
            ['shoes_1'] = 6, ['shoes_2'] = 0, 
        },
        boss = {
            ['tshirt_1'] = 19, ['tshirt_2'] = 2,
            ['torso_1'] = 7, ['torso_2'] = 1,
            ['arms'] = 6,
            ['chain_1'] = 0,
            ['pants_1'] = 31, ['pants_2'] = 0,
            ['shoes_1'] = 6, ['shoes_2'] = 0, 
        },
        boss2 = {
            ['tshirt_1'] = 19, ['tshirt_2'] = 2,
            ['torso_1'] = 7, ['torso_2'] = 0,
            ['arms'] = 6,
            ['chain_1'] = 0,
            ['pants_1'] = 6, ['pants_2'] = 0,
            ['shoes_1'] = 6, ['shoes_2'] = 0, 
        },
    },
}