Config.Zones['Pochutiny'] = {
    Pos   = {x = 0.0, y = 0.0, z = 0.0},
    Size  = { x = 0.6, y = 0.6, z = 0.3 },
    Color = { r = 255, g = 119, b = 0 },
    Type  = 1,
    Items = {
        { name = 'bolcacahuetes',   label = 'Arasidy',    price = 10 },
        { name = 'bolnoixcajou',    label = 'Kesu',     price = 20 },
        { name = 'bolpistache',     label = 'Pistacie',      price = 15 },
        { name = 'bolchips',        label = 'Chipsy',         price = 15 },
        { name = 'saucisson',       label = 'Kabanos',        price = 20 },
        { name = 'grapperaisin',    label = 'Rozinky',     price = 10 },
        { name = 'pizza_slice_cheese',    label = 'Pizza Syrova',     price = 50 },
        { name = 'pizza_slice_margarita',    label = 'Pizza Margarita',     price = 50 },
        { name = 'pizza_slice_salami',    label = 'Pizza Salamova',     price = 50 },
    },
}

Config.Zones['Alkohol'] = {
    Pos   = { x = 1181.56, y = -3267.62, z = 4.53},
    Size  = { x = 1.5, y = 1.5, z = 0.4 },
    Color = { r = 238, g = 0, b = 0 },
    Type  = 1,
    Items = {
        { name = 'jager',      label = 'Jagermeister',   price = 250 },
        { name = 'vodka',      label = 'Vodka',   price = 250 },
        { name = 'rhum',       label = 'Rum bily',    price = 250 },
        { name = 'tequila',    label = 'Tequila', price = 250 },
        { name = 'tequila_gold',    label = 'Tequila Gold', price = 250 },
        { name = 'prosecco',    label = 'Prosecco', price = 250 },
        { name = 'aperol',    label = 'Aperol', price = 250 },
        { name = 'liqueur_apple',    label = 'Jablecny liker', price = 250 },
        { name = 'triple_sec',    label = 'Triple sec', price = 250 },
        { name = 'becherovka',    label = 'Becherovka', price = 250 },
        { name = 'liqueur_curacao',    label = 'Curacao liker', price = 250 },
        { name = 'vajecny_liker',    label = 'Vajecny liker', price = 250 },
        { name = 'brandy',    label = 'Brandy', price = 250 },
        { name = 'liqueur_orange',    label = 'Pomerancovy liker', price = 250 },
        { name = 'gin',    label = 'Gin', price = 250 },
        { name = 'jack_apple',    label = 'Jack Daniels Apple', price = 250 },
        { name = 'jack_honey',    label = 'Jack Daniels Honey', price = 250 },
        { name = 'jack',    label = 'Jack Daniels', price = 250 },
        { name = 'cinzano',    label = 'Cinzano', price = 250 },
        { name = 'champagne',    label = 'Sampanske', price = 250 },
        { name = 'campari',    label = 'Campari', price = 250 },
        { name = 'liqueur_peach',    label = 'Broskvovy liker', price = 250 },
        { name = 'absinth',    label = 'Absinth', price = 250 },
        { name = 'zelena',    label = 'Zelena', price = 250 },
        { name = 'liqueur_coffee',    label = 'Kavovy liker', price = 250 },
        { name = 'fernet',    label = 'Fernet', price = 250 },
        { name = 'rhum_dark',    label = 'Rum', price = 250 },
        { name = 'borovicka',    label = 'Borovicka', price = 250 },
        { name = 'baileys',    label = 'Baileys', price = 250 },
        { name = 'beer',    label = 'Pivko', price = 750 }
    },
}

Config.Zones['Nealko'] = {
    Pos   = { x = 1181.93, y = -3264.04, z = 4.53 },
    Size  = { x = 1.5, y = 1.5, z = 0.4 },
    Color = { r = 238, g = 110, b = 0 },
    Type  = 1,
    Items = {
        { name = 'soda',        label = 'Soda',     price = 10 },
        { name = 'energy_drink',      label = 'Redbull',   price = 10 },
        { name = 'limonade',    label = 'Limonada', price = 10 },
        { name = 'tonic',     label = 'Tonic',      price = 10 },
        { name = 'juice_ananas',     label = 'Ananasovy dzus',      price = 10 },
        { name = 'juice_brusinka',     label = 'Brusinkovy dzus',      price = 10 },
        { name = 'cocacola',     label = 'Coca cola',      price = 10 },
        { name = 'juice_apple',     label = 'Jablecny dzus',      price = 10 },
        { name = 'juice_orange',     label = 'Pomerancovy dzus',      price = 10 },
        { name = 'water',     label = 'Voda',      price = 10 },
        { name = 'beer_nealko',    label = 'Nealko Pivko', price = 750 },
        { name = 'fanta',    label = 'Fanta', price = 10 },
        { name = 'sprunk',    label = 'Sprunk', price = 10 }
    },
}

Config.Zones['Ingredience'] = {
    Pos   = {x = 1181.91, y = -3272.59, z = 4.53},
    Size  = { x = 1.5, y = 1.5, z = 0.4 },
    Color = { r = 255, g = 255, b = 255 },
    Type  = 1,
    Items = {
        { name = 'ice',     label = 'Led',      price = 5 },
        { name = 'menthe',  label = 'Mata',   price = 5 },
        { name = 'pomrdanc',     label = 'Pomeranc',      price = 100 },
        { name = 'extract_pomrdanc',     label = 'Pomerancova stava',      price = 5 },
        { name = 'apple',     label = 'Jablko',      price = 10 },
        { name = 'lemon',     label = 'Citron',      price = 100 },
        { name = 'extract_lemon',     label = 'Citronova stava',      price = 5 },
        { name = 'lime',     label = 'Limetka',      price = 100 },
        { name = 'extract_lime',     label = 'Limetkova stava',      price = 5 },
        { name = 'coco_cream',     label = 'Kokosovy krem',      price = 5 },
        { name = 'mleko',     label = 'Mleko',      price = 150 },
        { name = 'slehacka',     label = 'Slehacka',      price = 225 },
        { name = 'tresen',     label = 'Tresen',      price = 100 },
        { name = 'olives',     label = 'Olivy',      price = 100 },
        { name = 'cukr',     label = 'Cukr',      price = 5 },
        { name = 'grenadina',     label = 'Grenadina sirup',      price = 5 },
        { name = 'smetana',     label = 'Smetana',      price = 225 },
        { name = 'freshcoffe',     label = 'Kavova zrna',      price = 100 },
        { name = 'gomme',     label = 'Gomme sirup',      price = 5 }
    },
}


local coffeeSellPrice = 330
local drinkSellPrice = 400
local drinkSpecialSellPrice = 800

Config.Zones['Sell'] = {
    Pos     = { x = 917.46, y = 3657.19, z = 31.98 },
    Size  = { x = 1.0, y = 1.0, z = 0.4 },
    Color = { r = 255, g = 255, b = 255 },
    Type  = 1,
    Items = {
        -- COFFEE
        {item = 'kava_alzirska', price = coffeeSellPrice},
        {item = 'kava_irska', price = coffeeSellPrice},
        {item = 'kava_s_baileys', price = coffeeSellPrice},
        -- DRINK
        {item = 'mixapero', price = drinkSellPrice},
        {item = 'ashi_drink', price = drinkSellPrice},
        {item = 'blowjob', price = drinkSellPrice},
        {item = 'appletini', price = drinkSellPrice},
        {item = 'beton', price = drinkSellPrice},
        {item = 'blue_hawai', price = drinkSellPrice},
        {item = 'blue_lagoon', price = drinkSellPrice},
        {item = 'bombardino', price = drinkSellPrice},
        {item = 'cosmopolitan', price = drinkSellPrice},
        {item = 'cuba_libre', price = drinkSellPrice},
        {item = 'gin_tonic', price = drinkSellPrice},
        {item = 'honey_punch', price = drinkSellPrice},
        {item = 'kamikadze', price = drinkSellPrice},
        {item = 'long_island', price = drinkSellPrice},
        {item = 'margarita', price = drinkSellPrice},
        {item = 'manhattan', price = drinkSellPrice},
        {item = 'martini', price = drinkSellPrice},
        {item = 'mojito', price = drinkSellPrice},
        {item = 'negroni', price = drinkSellPrice},
        {item = 'paradise', price = drinkSellPrice},
        {item = 'pina_colada', price = drinkSellPrice},
        {item = 'sex_on_the_beach', price = drinkSellPrice},
        {item = 'tequila_sunrise', price = drinkSellPrice},
        {item = 'vodnikovo_semeno', price = drinkSellPrice},
        {item = 'white_russian', price = drinkSellPrice},
        {item = 'zazelezobetonovany_rumburak', price = drinkSpecialSellPrice},
        {item = 'jager_cola', price = drinkSellPrice},
        {item = 'letajici_jelen', price = drinkSellPrice},
        {item = 'mimosa', price = drinkSellPrice},
        {item = 'teleport', price = drinkSellPrice},
        {item = 'vodkafruit', price = drinkSellPrice},
    }
}